services:
  web:
    build: ./website
    container_name: student_dashboard
    ports:
      - "80:80"
    restart: always
version: '3'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    restart: always
